[project]
name = "code-predictor-annotation-ui"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "streamlit>=1.55.0",
]

[dependency-groups]
dev = [
    "poethepoet>=0.42.1",
    "ruff>=0.15.4",
]


[tool.poe.tasks]
lint = "ruff check ."
format = "ruff format ."
start = "streamlit run app.py"


[tool.ruff.format]
preview = true
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = true
line-ending = "auto"
docstring-code-format=true

